
# install: 	gem install guard-shell
# run:  	guard


# Add files and commands to this file, like the example:
#   watch(%r{file/path}) { `command(s)` }

guard 'shell' do
  watch('index.md') { `./build.sh` }
end
